### ISSUE TITLE
TODO for 2.0

### ISSUE THREAD

**Issue by MarkelFe** [frc7787/frc7787#21]
![Critical](https://img.shields.io/badge/-critical-critical.svg?style=for-the-badge)
- [x] ~~Houston section~~
- [x] ~~#24 Use the <picture> element for serving not webp images [(important for iOS)](https://caniuse.com/#search=webp) [(check this resource)](https://medium.com/front-end-weekly/html-picture-tag-in-practice-png-and-webp-formats-5a3fc51b5998)~~
- [x] ~~Change Github links to the @frc7787 user instead of @reybots7787~~

![Easy](https://img.shields.io/badge/-easy-brightgreen.svg?style=for-the-badge)
- [x] ~~Check that the favicons and the different link elements work~~
- [x] ~~Remove the white background from the old logo image [on brand](//frc7787.ca/brand.html)~~

![Medium](https://img.shields.io/badge/-medium-orange.svg?style=for-the-badge)
- [x] ~~Set up the [Google Search Console](https://search.google.com/search-console/about) (unique verification record: _google-site-verification=gQrGbCnPrwxWC_uJqUiKrk1COBQENKJNATW2JIvtutw_) [learn more](https://support.google.com/webmasters/answer/9008080#domain_name_verification)~~
- [ ] Introduce [new effects](https://codepen.io/vitor-siqueira/pen/xNBExN)

**Comment by MarkelFe** [comment]
Even if the introduce new effects is not done, I will be releasing the 2.0 update 😊
