### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MarkelFe** [frc7787/frc7787#25]
![Easy](https://img.shields.io/badge/-easy-brightgreen.svg?style=for-the-badge)
- [ ] Use window.hostname instead of a direct link to frc7787.ca for the case that we want to move to other domains

![Medium](https://img.shields.io/badge/-medium-orange.svg?style=for-the-badge)
- [ ] Create a _Become a sponsor_ page
- [ ] 404 Page

![Hard](https://img.shields.io/badge/-hard-red.svg?style=for-the-badge)
- [ ] Make that the sponsors appear by a JSON, making it more suitable to changes (this includes updating with out new sponsors)
- [ ] Create a new team members page
- [ ] Our past and present robots

**Comment by kkarim** [comment]
Oh, I like the sponsor JSON idea.
